### ISSUE TITLE
manual/#divide-primitive

### ISSUE THREAD

**Issue by YruamaLairba** [grame-cncm/faustwebsite#11]
[Here](https://faust.grame.fr/doc/manual/#divide-primitive), the example is wrong, it show "power" primitive.

**Comment by rmichon** [comment]
Thanks pointing that out, this has been fixed here : https://github.com/grame-cncm/faustdoc/commit/e200a364d177fca0f70c3e2027f233fe18c045e6 
It might take some time for this change to propagate to the website.
