### ISSUE TITLE
Error Message Documentation typo

### ISSUE THREAD

**Issue by wy2lam** [grame-cncm/faustwebsite#17]
Page: https://faustdoc.grame.fr/manual/errors/#recursive-connection-error

Mistake:
"...will produce a box connection error if the number of outputs of A is less than the number of inputs of B, or the number of outputs of B is **less** than the number of inputs of A..."

Correction:
"...will produce a box connection error if the number of outputs of A is less than the number of inputs of B, or the number of outputs of B is **more** than the number of inputs of A..."

**Comment by sletz** [comment]
Fixed, thanks.
