### ISSUE TITLE
FaustLive is not maintained anymore

### ISSUE THREAD

**Issue by Barabas5532** [grame-cncm/faustwebsite#19]
https://faustdoc.grame.fr/manual/overview/ mentions that FaustLive is the best environment for prototyping with Faust. However, according to https://github.com/grame-cncm/faustlive/issues/60, FaustLive is no longer maintained.

What should I use for rapid prototyping instead of FaustLive?

**Comment by sletz** [comment]
https://faustide.grame.fr
