### ISSUE TITLE
Tutorial for ESP32 c++ example link is broken.

### ISSUE THREAD

**Issue by mikemoretti3** [grame-cncm/faustwebsite#8]
Under the heading:
Using the ESP32 C++ Development Environment
there is a link: The final source code of this tutorial can be found "here".  This "here" link is broken.
instead of:
https://faust.grame.fr/doc/tutorials/misc/esp32-C++.zip
it should be
https://faust.grame.fr/doc/tutorials/misc/esp32-c++.zip
(lowercase c++).
Thanks!

**Comment by sletz** [comment]
Thanks. The link has been fixed in the GitHub source, but the site has not been redeployed since. @rmichon ?

**Comment by rmichon** [comment]
Yes! I was planning to redeploy the site pretty soon, hopefully within the next 2 weeks...
